# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "resque-web_no_act"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rainer Kuhn"]
  s.date = "2012-09-03"
  s.description = "A stripped version of the Resque web interface that's safe to use by not so trustworthy personnel. You get all the same information as the regular interface, but can't delete or retry anything."
  s.email = "ticktricktrack@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/resque-web_no_act.rb",
    "lib/resque/server_no_act.rb",
    "lib/resque/server_no_act/public/favicon.ico",
    "lib/resque/server_no_act/public/idle.png",
    "lib/resque/server_no_act/public/jquery-1.3.2.min.js",
    "lib/resque/server_no_act/public/jquery.relatize_date.js",
    "lib/resque/server_no_act/public/poll.png",
    "lib/resque/server_no_act/public/ranger.js",
    "lib/resque/server_no_act/public/reset.css",
    "lib/resque/server_no_act/public/style.css",
    "lib/resque/server_no_act/public/working.png",
    "lib/resque/server_no_act/views/no_act.erb"
  ]
  s.homepage = "http://github.com/ticktricktrack/resque-web_no_act"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Look don't touch!"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<resque>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<resque>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

